config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  root to: 'tasks#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(tasks_params)
    if @task.save
      redirect_to task_path(@task)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @task.update(tasks_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
  end

  private

  def find_task
    @task = Task.find(params[:id])
  end

  def tasks_params
    params.require(:task).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1 class="name_app"><%= link_to 'ToDo App', '/' %></h1>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="form-inline">
  <%= form_for(@task) do |f|%>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
    <%= f.submit %>
  <% end %>
</div>

app/views/tasks/index.html.erb
<div class="text-center">
  <h3 class="btn btn-info"><%= link_to 'Add a TASK', new_task_path %></h3>
</div>

<div class="wrapper-card">
  <ul>
    <% @tasks.each do |t| %>
      <li class="card">
        <span class="title"><%= link_to t.title, task_path(t) %></span>
        <span class="suppr"><%= link_to raw('<i class="fa fa-times" aria-hidden="true"></i>'), task_path(t), method: :delete, data: { confirm: "Are you sure?" } %></span>
        <span class="update"><%= link_to'Edit', edit_task_url(t)%></span>
      </li>
    <% end %>
  </ul>
</div>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f|%>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<h2><%= @task.description %></h2>